sudo: required
services:
- docker
language: node_js
node_js: node
script:
- make lint
- make critique
before_deploy:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu
  $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce
- make docker
deploy:
- provider: script
  script: make google-drive
  skip_cleanup: true
  on:
    tags: true
- provider: releases
  api_key:
    secure: H0+EZ/J4QPaPrLEbzJ9fUf9A6r9aS5DcSVdXlTCKMXTf6BJ2RXFU2Vem3ZY0IW+guLOVi00xlHBkG92N8+P/G3W4VlFwvDof93D5FC3glapUCAIkYA5poeUVaWGeWdKP4gz79zsRjN/ehR5Rr9GxTPlVMlIER1jQ4Vd4h0Wb3TA0agDFIvZ8+EGqsbJMXCBRwBBBbTfMaCSrSczPcJnq+giCo/11JJbMDb9E1FcpsLK5kJ8djsc96Sxh9c1v+R+g+XO6D5tcgopYJYFIZz/pM472qqz19Q1B4m3OTCrTK5SCkKc3EVUBMMJSgFXmQ+UJDnJj1yaHWf9CT45ZRVy0gBZog8e1kFIxXFAqUPOiOemksAdrLGF0akUxfoCAKJy8FFr+F2V2IGjVYXAVvt2QpUx3tNoxA601EVeUEs5NkMGh4NI23c5Ey506RuRpcJCZG4olHSO0a5zXmr97bag9EROW28uylqcmblRav7HSOsx3BbBc8UkFmX7qA4g3QnDd6xJ1+dIq1uGBch8dUa65qIA1xcrThxArKXWUFMUW/yIQyzQAluGlSas6l0JGhiYDIswgQJTr0Q7LdxNZjFN4QS/Se/PKJKMQ5K2XnBRoKnXhk+3ubJO9VJweRkqmnSbtPzCuQFmsARN3zpBo6szFMAiI566aReJdYNjV0KqBrmk=
  skip_cleanup: true
  file_glob: true
  file: build/*
  on:
    tags: true
env:
  global:
  - secure: Rj/yK2g1OvMAa63OWpZ7K8XGzPJgQRJ476hMCCCttjY8GiAWZhP3qoyPYfIS2OKxG8/ko997yjUjeSY8HC3lfZuDnZk1WDYLYUBiuOP2Hmo7EpwUUWxsn3Zh+Chkpk57sXZdEe6iXGuruKapblyl+hFK4OTXDzxTujuTq4Si472WqF3us7x6wlb9V9AUEYjcbJc+3rNzaPdL7WhG7qMU+k2SOQjkA7Urvg7qOTHVC7T4nQKhX5npu0X+9WmQ8hbPmP1sgzYl3ac/kikoT+zRxk9/oic2uUw0Nh10Fq28lWyph6NKZ31SVj1RnOxTi/36CfY0PawiZw9V4UaihCBFvuEY7d+sU6W9a3P571MuxyQkGkQxT3GgbjsBrSErSwXJAB7Fl4+eXcXNlArKq8ZlqQvMIbD5iNaY7CmF57opHhfYeP5lSKSYDLcUYC5nAVE798vAvyTZ0zh8FSO14TbSyu1IhnLDekx9KjHzMoeU4xOm1cCwoxH5tzTcI26rMD0lP/Rj2TZXzlb5/xwU7wKY4f6GaL0DgcHGeRkkmPJ1JX+TXRPTTTXtXsEVsQ/enjcOySxnvkJQK1Wlt4+yKU/llJ5sBj74JZCqpzpj9M8D3YziblvE/gNrUVztsG1cLsL8fMuDIEVCkfQe2dLfW8HH1zI8VxR5MOcYxuHrpRJM9/Y=
  - secure: tlvZpGHAYNt93bvwmHd10CiBfCIDu2o7WnhM7DclVoKwXWKa5ZYxgcQqoPb3V+sdyrNSz5dLYiHA/A0vnrKgIJPw9hFDSZFXmSD5rETHqkFlUDFkSR+oCcEpteLqeDKyuUxxrgs12ZyevtrSTfwGBwyEb0FMZ+5P3yh81Utj8IfvzJgkKS/jgA16wsNGtX/fLBgYlWhOHNkA+4tmEciGA8uihBq/GQ3iguhdxZIOIEo+mDpx0dEIAGSODB+ao1NMt45EK9uwBZBay7fUkXFsi11LEfHIijqvCwnL+GRAdtMnJFpX9rAliJowUoceOMMpMTDerMvzkIWIRDcSV3WJA5oEXn0+jYJRb625C+bEnOe0YIO+ROZn3APEXL0Dc6kA4GXG6fpc76+RJ2zXJpr/5EMSh27ZAa4A6uS7qe2jHmVMchGLfZdKiLHbNbDfPO46f/pX2mA5oM3vyFOmfti5WNMtroZ2bS6Y2VfYn4l5Kz57aqHcndeZ1XL1uyG3z5n8CQqoRYviidBYGwlbaqTxf92x9oLcmGJT0rowb//vdqhqE11CF2A5AzOEQbQyFMwvchTawCEN4AvDNcBXB4kb6umtU7np5voofgZ2OPiB01Vk/rbtzbPS/iRJq565UFzEfOQ0n9zwKa5bpO68rHX02WrY6by7Z/p0fnCNZ4IGLss=
  - secure: VMynV8yJtSy9PgqiGtSMUPifAumWprkCs2A47G/LKZKQNRT0PT67J3piTEMsIz8S+3vCaO7j8OnGOVmcZgC/abDUjcUw7CvUB26mPQ3HIliUaWrTDNJA42o1B+MY3/6VQN5IRGCXMCzxqIzhSae9C4rh2xqpjBP+FtvWK0woI4GFK33aiVvc59iMTYBAtWb7jtxy40D1nog1GHMOWFX/I8ElHW057rt9kHI5/8legi1oD1+1fJxOAJ+MTq/CvDQvQR7f9GHHXLiAenReAyJ4DTj0AcldN5nM2/YBepj1R5bjaIhNA9Nijaz4z0XpAkrcBENu0rDzmn4G77tiOXB+38me6fKmGRO9XHETO9+3OuSW02tAgPNqGCGMWpZsLCO+VQCAg0f8rES9XQ11By4nRJJIhaNLBHnoyXytPunMD8Pl/xwmZkNgjCTN4zCOwblkOH8CA703+krVCB7nVu4Lxy7Z1GvD6WBNk8QEiIzKA6GYmziy/8FyFLvVHx86VaLRKnVjxX/BapI3mtCQafZbkddIoIBmsQzTIbGfJB7auaGQX6paZZ/JeB1JEqT7qx9LAwsyUNkrbW7zkipFGSfh0copHrNCm1dGc3Ud3iX1Dd+92e+LaaK6vtFSILMQkSHOllEjzGz8kSGwZu4aGNMj360UXE47kyZDh/60AXa3gSA=
